#!/usr/bin/env bash
# add redirection to nginx
sed -i '/server_name _;/a\
\tlocation /redirect_me {\
  \t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
\t}' /etc/nginx/sites-available/default
