#!/usr/bin/env bash
# installl nginx
apt-get update && apt-get install nginx -y
ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

# create 404 page
touch /var/www/html/404.html && echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html


printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html;
    index index.html;
    location = /404.html {
        internal;
    }
    error_page 404 /404.html;
    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
    }
}" > /etc/nginx/sites-available/default

service nginx restart